server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/graduation_114_sfm_dw?useUnicode=true&amp&characterEncoding=utf-8&serverTimezone=GMT%2b8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  thymeleaf:
    cache: false
    encoding: UTF-8
    mode: HTML5
    suffix: .html
    servlet:
      content-type: text/html; charset=utf-8

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: WEB-INF/**

  freemarker:
    cache: false

  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.example.wage.pojo, com.quality.wage.vo
  global-config:
    db-config:
      id-type: assign_uuid
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0

